# Generated by Django 4.2.14 on 2024-07-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('frame_id', models.AutoField(primary_key=True, serialize=False)),
                ('frame_data', models.TextField()),
                ('timestamp', models.BigIntegerField()),
            ],
            options={
                'db_table': 'frames',
            },
        ),
    ]
