# Generated by Django 4.2.14 on 2024-07-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_data', models.TextField()),
                ('timestamp', models.BigIntegerField()),
            ],
        ),
    ]
