# # Generated by Django 4.2.14 on 2024-07-18 14:37

# from django.db import migrations


# class Migration(migrations.Migration):

#     dependencies = [
#         ('frames', '0001_initial'),
#     ]

#     operations = [
#     ]
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "SELECT 1",
            reverse_sql="SELECT 1",
        ),
    ]
